export const ClOSED_TABLE_ROWS = [
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "9999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Buy",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "9999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "9999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "9999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "999.999", down: "999" },
  },
  {
    order: { id: "#123455778", signal: "Black Signal" },
    time: {
      date: new Date().toLocaleDateString(),
      time: new Date().toLocaleDateString(),
    },
    type: "Sell",
    size: "9999.99",
    symbol: "GBPUSD",
    price: "1.2656",
    sl: "1.2",
    tp: "1.2 ",
    profit: { up: "999.999", down: "999" },
  },
];
